name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: wilfred2018/voicfy
  VERSION: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi

          # Install Docker Compose
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Setup project directory
          mkdir -p ~/invoify-app
          cd ~/invoify-app

          # Clean old repo (optional)
          rm -rf ./*

          # Pull latest repo files
          git clone https://github.com/${{ github.repository }} . --branch main --single-branch

          # Create/overwrite .env file if needed
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" > .env
          echo "VERSION=${{ env.VERSION }}" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env

          # Login to Docker Hub
          docker login -u $DOCKER_USERNAME -p ${{ secrets.DOCKER_TOKEN }}

          # Pull latest image version
          docker pull $IMAGE_NAME:$VERSION

          # Stop previous containers
          docker-compose down || true

          # Start containers using your repo's docker-compose.yml
          docker-compose --env-file .env up -d
