name: Deploy Invoify App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/voicfy
  VERSION: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi

          # Install Docker Compose
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Setup project directory
          mkdir -p ~/invoify-app
          cd ~/invoify-app

          # Clean old repo (optional)
          rm -rf ./*

          # Pull latest repo files
          git clone https://github.com/wilfredoamen/invoicfy-app . --branch main --single-branch

          # Write .env
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" > .env
          echo "VERSION=${{ env.VERSION }}" >> .env
          echo "DOCKER_USERNAME=${{ env.DOCKER_USERNAME }}" >> .env

          # Login to Docker Hub
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Pull image and run
          docker pull $IMAGE_NAME:$VERSION
          docker-compose down || true
          docker-compose --env-file .env up -d
